# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe1d136de2d807538ed039cc4e90bd1c2fa8c72dccb20655c116d83f09f4b35966e28920a1bb42a5d196947c5e5d348d52b7ea275afed9eba197190ab31e0e3
  facebook_app_id: 175617472881358
  facebook_app_secret: cfac56cc052e8a38202bb11e6bac91cd

test:
  secret_key_base: 00c365d92ee84677f6c670769c8722f56d63eee94296250e2a7d98904e26ecb66a092707a081704a8753a02bc5dcd84dc5d49c2d751df0c93f818e5a395e3cc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
