test:
  mysql41: 9307
production:
  pid_file: /home/deployer/qna/shared/tmp/pids/searchd.pid
  indices_location: /home/deployer/qna/shared/db/sphinx
  configuration_file: /home/deployer/qna/shared/config/production.sphinx.conf
  binlog_path: /home/deployer/qna/shared/log
