test:
  mysql41: 9306
production:
  mysql41: 9307
  version: 2.2.11
  pid_file: tmp/pids/searchd.pid
  indices_location: db/sphinx
  configuration_file: config/production.sphinx.conf
  binlog_path: log